---
  - name: create user
    hosts: local
    become: yes
    
    tasks:
      - name: Show all the hosts in the current play
        ansible.builtin.debug:
           msg: "{{ item }}"
        loop: "{{ ansible_play_batch }}"
      - name: add a list of item
        user: name='{{item}}'  state=present
        with_items:
               - abc
               - pqr
               - xyz
               - user

